In [1]:
import os
import librosa
import numpy as np
import soundfile as sf

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
path = "/content/drive/MyDrive/SafeReels-664/Processed_Audio/audio1000188341415358.wav"
audio, sr = librosa.load(path, sr=None)
audio

array([ 0.33615112,  0.46264648,  0.53808594, ..., -0.00369263,
       -0.0229187 , -0.07574463], dtype=float32)

In [4]:
sr

22050

In [6]:
mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)
mfcc

array([[ -63.071457 ,  -50.630257 ,  -61.538456 , ..., -188.20895  ,
        -200.40793  , -221.072    ],
       [ 161.41092  ,  189.99426  ,  212.10625  , ...,  -40.93435  ,
         -31.17498  ,   -7.166887 ],
       [ -13.331305 ,  -36.51619  ,  -60.116898 , ...,  -90.74747  ,
         -86.79704  ,  -65.16135  ],
       ...,
       [  -8.8894005,    2.3347702,   12.744503 , ...,   18.464409 ,
          19.76472  ,   20.666336 ],
       [  -0.5574487,    5.324918 ,    1.7564235, ...,   31.59786  ,
          29.786667 ,   18.09544  ],
       [  -8.922134 ,  -10.265442 ,   -2.4901743, ...,   64.388664 ,
          56.462105 ,   43.06263  ]], dtype=float32)

In [7]:
chroma = librosa.feature.chroma_stft(y=audio, sr=sr, n_chroma=12)
chroma

array([[0.8785468 , 0.886118  , 0.8489311 , ..., 0.08802089, 0.1269775 ,
        0.19098186],
       [0.54127514, 0.58180046, 0.8959275 , ..., 0.23511769, 0.28603628,
        0.36132702],
       [0.29268166, 0.42233068, 0.7474989 , ..., 1.        , 0.7609574 ,
        0.2631755 ],
       ...,
       [0.41416943, 0.9124689 , 1.        , ..., 0.39296368, 0.41027793,
        0.38297266],
       [0.64277184, 0.9313495 , 0.90914273, ..., 0.22488263, 0.20192951,
        0.18414871],
       [1.        , 1.        , 0.7005295 , ..., 0.06921876, 0.10382624,
        0.09321272]], dtype=float32)

In [8]:
spectral_centroid = librosa.feature.spectral_centroid(y=audio, sr=sr)
spectral_centroid

array([[1150.03629074,  952.53311908,  870.78746201,  840.26397421,
         808.76954633,  900.13704887, 1089.77443101, 1110.12091092,
        1109.77506131, 1047.66588809,  945.98514215,  956.61995284,
         989.04402396,  953.11497607, 1025.96909555, 1028.93658232,
         951.78694738,  975.36873706,  991.99897042,  846.54030184,
         666.2091215 ,  788.46858239, 1162.17133735, 2048.98778046,
        2272.51839354, 2023.3497391 , 1515.9491469 , 1119.08405985,
         977.20631955,  684.22603587,  670.57152683, 1156.24794741,
        1625.1905109 , 1831.30334324, 1528.5258249 ,  890.63337621,
         677.47848674,  770.69642744,  999.30950884, 1427.38244067,
        1665.3274898 , 1752.2263652 , 1178.64514609, 1067.40666253,
        1181.92195217, 1516.2134583 , 1509.25808004, 1118.67379082,
         762.00088157,  629.3381679 ,  611.21598652,  933.93774471,
        1435.69466393, 2198.78169626, 2915.50716328, 3323.04070485,
        3310.91620497, 3232.78560547, 2300.40279

In [11]:
spectral_contrast = librosa.feature.spectral_contrast(y=audio, sr=sr, n_bands=6, fmin=200.0)
spectral_contrast

array([[ 8.02630898, 11.98865011, 12.45628054, ..., 16.51522666,
        11.02006242,  3.51177483],
       [ 9.40339584,  6.55506098, 11.2673789 , ..., 26.17162543,
         7.42202694,  1.74494328],
       [21.90166417, 13.32579656, 15.60105933, ..., 24.51756082,
        25.16511613, 24.39112777],
       ...,
       [17.88033959, 19.43780502, 17.24432813, ..., 29.28673661,
        28.9564174 , 26.04685855],
       [13.90463992, 18.34517548, 23.15499922, ..., 43.67940803,
        29.07218648, 23.47827335],
       [ 1.87766844,  2.41095849, 14.68441529, ..., 44.59852084,
        29.10778877, 21.21370484]])

In [13]:
spectrogram = np.abs(librosa.stft(audio))
spectrogram

array([[3.32345352e+01, 4.41525459e+01, 1.03833908e+02, ...,
        1.47083225e-02, 2.70057414e-02, 5.83295189e-02],
       [3.76100006e+01, 1.00215851e+02, 1.26646408e+02, ...,
        8.33756570e-03, 1.03412764e-02, 5.35505302e-02],
       [2.77666321e+01, 1.06362762e+02, 1.41534592e+02, ...,
        3.80973378e-03, 1.92146618e-02, 5.05804420e-02],
       ...,
       [1.10517815e-01, 5.58452830e-02, 7.60110468e-03, ...,
        9.09579830e-05, 2.29315981e-02, 9.05284360e-02],
       [1.10154703e-01, 5.27724326e-02, 3.45591991e-03, ...,
        2.87258852e-04, 1.95420105e-02, 8.46062005e-02],
       [1.10894166e-01, 5.75271435e-02, 6.27581496e-03, ...,
        1.34652597e-04, 1.81787852e-02, 8.22030976e-02]], dtype=float32)

In [18]:
def extract_features(audio_path, n_mfcc=13, n_chroma=12, n_spectral_contrast=6, target_length=20):
    # Load audio file
    audio, sr = librosa.load(audio_path, sr=None)

    # Extract MFCCs (13 coefficients)
    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=n_mfcc)

    # Extract Chroma Features (12 pitch classes)
    chroma = librosa.feature.chroma_stft(y=audio, sr=sr, n_chroma=n_chroma)

    # Extract Spectral Centroid
    spectral_centroid = librosa.feature.spectral_centroid(y=audio, sr=sr)

    # Extract Spectral Contrast (7 bands)
    spectral_contrast = librosa.feature.spectral_contrast(y=audio, sr=sr, n_bands=n_spectral_contrast)

    # Extract Spectrogram (Magnitude Spectrogram)
    spectrogram = np.abs(librosa.stft(audio))

    # Truncate or pad features to target_length
    def truncate_or_pad(feature, target_length):
        if feature.shape[1] > target_length:
            return feature[:, :target_length]
        else:
            return np.pad(feature, ((0, 0), (0, target_length - feature.shape[1])), mode='constant')

    mfcc = truncate_or_pad(mfcc, target_length)
    chroma = truncate_or_pad(chroma, target_length)
    spectral_centroid = truncate_or_pad(spectral_centroid, target_length)
    spectral_contrast = truncate_or_pad(spectral_contrast, target_length)
    spectrogram = truncate_or_pad(spectrogram, target_length)

    # Flatten features into a single vector
    feature_vector = np.concatenate([
        mfcc.flatten(),
        chroma.flatten(),
        spectral_centroid.flatten(),
        spectral_contrast.flatten(),
        spectrogram.flatten()
    ])

    return feature_vector

In [19]:
def process_audio_directory(input_dir, output_dir):
    # Create output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Process each audio file in the input directory
    for file_name in os.listdir(input_dir):
        if file_name.endswith(('.wav')):  # Add more formats if needed
            file_path = os.path.join(input_dir, file_name)

            # Extract features
            feature_vector = extract_features(file_path)

            # Save feature vector to a file
            output_file_path = os.path.join(output_dir, file_name.replace('.wav', '.npy'))
            np.save(output_file_path, feature_vector)
            print(f"Extracted features and saved: {output_file_path}")

In [20]:
input_directory = "/content/drive/MyDrive/SafeReels-664/Processed_Audio"
output_directory = "/content/drive/MyDrive/SafeReels-664/Extracted_Features"
process_audio_directory(input_directory, output_directory)

Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1000188341415358.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1006146964533997.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1007123741459823.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1007420607202244.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1008519870870927.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1008937321004084.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1010700924171308.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1011201907424293.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1014617364040

/usr/local/lib/python3.11/dist-packages/librosa/core/pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(


Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1509046346477876.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1510782766526910.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1509735403314316.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1511696116158211.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1517437585515127.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1515846142374319.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1521441631790386.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1526381382090088.npy
Extracted features and saved: /content/drive/MyDrive/SafeReels-664/Extracted_Features/audio1529721697640

In [21]:
def analyze_directory(directory):

    file_counts = {}
    total_files = 0

    for filename in os.listdir(directory):
        filepath = os.path.join(directory, filename)
        if os.path.isfile(filepath):
            total_files += 1
            _, ext = os.path.splitext(filename)
            ext = ext.lower()  # Normalize to lowercase
            file_counts[ext] = file_counts.get(ext, 0) + 1

    print(f"Total number of files in '{directory}': {total_files}")
    for ext, count in file_counts.items():
        print(f"{ext}: {count}")

In [22]:
analyze_directory('/content/drive/MyDrive/SafeReels-664/Extracted_Features')

Total number of files in '/content/drive/MyDrive/SafeReels-664/Extracted_Features': 664
.npy: 664
