In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
df = pd.read_csv('/content/Safereels annotation - Text_Annotation_data.csv')
df

reel_id  isSafe UnsafeType  \
0    www.facebook.com/reel/1000188341415358       1       Safe   
1    www.facebook.com/reel/1006146964533997       1       Safe   
2    www.facebook.com/reel/1007123741459823       0      Adult   
3    www.facebook.com/reel/1007420607202244       1       Safe   
4    www.facebook.com/reel/1008519870870927       1       Safe   
..                                      ...     ...        ...   
659   www.facebook.com/reel/997262608752854       0      Adult   
660   www.facebook.com/reel/997300345735398       0    Harmful   
661   www.facebook.com/reel/998187401354206       1       Safe   
662   www.facebook.com/reel/999558344609179       1       Safe   
663   www.facebook.com/reel/999669865038215       1       Safe   

                                          Visual texts  \
0       Me on my way to watch Oppenheimer After Berbie   
1                                                  NaN   
2         বান্ধবী আমার লাগানির পিনিকে আছে Love in love   
3         প্রত্যেকটা অফিসে এমন একজন কলিগ থাকবেই Laptop   
4            হ্যালো শার্ক ট্যাঙ্ক বাংলাদেশ আই এম কামিং   
..                                                 ...   
659                                                NaN   
660                                                NaN   
661  খবরঃ কয়লা নিয়ে মোংলা বন্দরে এলো চীনের জাহাজ দে...   
662          সাকিব আল হাসান to বাংলাদেশী ক্রিকেট ফ্যান   
663                                                NaN   

                                           Audio texts  
0                                                  NaN  
1    এ মামা দুইটা সিঙ্গারা আর দুইটা সমুচা একটু তাড়া...  
2    পাগলা হাওয়ার বাদল দিনে পাগল আমার মন জেগে ওঠে প...  
3    যুদ্ধ আনে ধ্বংস সজনী সজনী তোমারে দেখিয়া মাতাল ...  
4                                                  NaN  
..                                                 ...  
659                                                NaN  
660                                                NaN  
661                                                NaN  
662                                                NaN  
663                                                NaN  

[664 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664 entries, 0 to 663
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   reel_id       664 non-null    object
 1   isSafe        664 non-null    int64 
 2   UnsafeType    664 non-null    object
 3   Visual texts  160 non-null    object
 4   Audio texts   4 non-null      object
dtypes: int64(1), object(4)
memory usage: 26.1+ KB


In [ ]:
df1 = df[:170]

In [ ]:
df2 = df[578:]

In [ ]:
merged_df = pd.concat([df1, df2], axis=0, ignore_index=True)

merged_df

reel_id  isSafe UnsafeType  \
0    www.facebook.com/reel/1000188341415358       1       Safe   
1    www.facebook.com/reel/1006146964533997       1       Safe   
2    www.facebook.com/reel/1007123741459823       0      Adult   
3    www.facebook.com/reel/1007420607202244       1       Safe   
4    www.facebook.com/reel/1008519870870927       1       Safe   
..                                      ...     ...        ...   
251   www.facebook.com/reel/997262608752854       0      Adult   
252   www.facebook.com/reel/997300345735398       0    Harmful   
253   www.facebook.com/reel/998187401354206       1       Safe   
254   www.facebook.com/reel/999558344609179       1       Safe   
255   www.facebook.com/reel/999669865038215       1       Safe   

                                          Visual texts  \
0       Me on my way to watch Oppenheimer After Berbie   
1                                                  NaN   
2         বান্ধবী আমার লাগানির পিনিকে আছে Love in love   
3         প্রত্যেকটা অফিসে এমন একজন কলিগ থাকবেই Laptop   
4            হ্যালো শার্ক ট্যাঙ্ক বাংলাদেশ আই এম কামিং   
..                                                 ...   
251                                                NaN   
252                                                NaN   
253  খবরঃ কয়লা নিয়ে মোংলা বন্দরে এলো চীনের জাহাজ দে...   
254          সাকিব আল হাসান to বাংলাদেশী ক্রিকেট ফ্যান   
255                                                NaN   

                                           Audio texts  
0                                                  NaN  
1    এ মামা দুইটা সিঙ্গারা আর দুইটা সমুচা একটু তাড়া...  
2    পাগলা হাওয়ার বাদল দিনে পাগল আমার মন জেগে ওঠে প...  
3    যুদ্ধ আনে ধ্বংস সজনী সজনী তোমারে দেখিয়া মাতাল ...  
4                                                  NaN  
..                                                 ...  
251                                                NaN  
252                                                NaN  
253                                                NaN  
254                                                NaN  
255                                                NaN  

[256 rows x 5 columns]

In [ ]:
df = merged_df
df['UnsafeType'].value_counts()

UnsafeType
Safe        160
Adult        66
Harmful      28
Suicidal      2
Name: count, dtype: int64

In [ ]:
df[df['UnsafeType']=='Suicidal']

reel_id  isSafe UnsafeType  \
134  www.facebook.com/reel/1241014316852317       0   Suicidal   
187   www.facebook.com/reel/888564683235261       0   Suicidal   

                                          Visual texts Audio texts  
134  সে যখন অন্য ছেলেদের সাথে কথা বলে.! আমি* আমার j...         NaN  
187  বন্ধু ছাড়া জীবন চলে না বন্ধু ছাড়া জীবন বন্ধদের...         NaN

In [ ]:
df['Visual texts'] = df['Visual texts'].fillna("কোন টেক্সট পাওয়া যায়নি")
df

reel_id  isSafe UnsafeType  \
0    www.facebook.com/reel/1000188341415358       1       Safe   
1    www.facebook.com/reel/1006146964533997       1       Safe   
2    www.facebook.com/reel/1007123741459823       0      Adult   
3    www.facebook.com/reel/1007420607202244       1       Safe   
4    www.facebook.com/reel/1008519870870927       1       Safe   
..                                      ...     ...        ...   
251   www.facebook.com/reel/997262608752854       0      Adult   
252   www.facebook.com/reel/997300345735398       0    Harmful   
253   www.facebook.com/reel/998187401354206       1       Safe   
254   www.facebook.com/reel/999558344609179       1       Safe   
255   www.facebook.com/reel/999669865038215       1       Safe   

                                          Visual texts  \
0       Me on my way to watch Oppenheimer After Berbie   
1                               কোন টেক্সট পাওয়া যায়নি   
2         বান্ধবী আমার লাগানির পিনিকে আছে Love in love   
3         প্রত্যেকটা অফিসে এমন একজন কলিগ থাকবেই Laptop   
4            হ্যালো শার্ক ট্যাঙ্ক বাংলাদেশ আই এম কামিং   
..                                                 ...   
251                             কোন টেক্সট পাওয়া যায়নি   
252                             কোন টেক্সট পাওয়া যায়নি   
253  খবরঃ কয়লা নিয়ে মোংলা বন্দরে এলো চীনের জাহাজ দে...   
254          সাকিব আল হাসান to বাংলাদেশী ক্রিকেট ফ্যান   
255                             কোন টেক্সট পাওয়া যায়নি   

                                           Audio texts  
0                                                  NaN  
1    এ মামা দুইটা সিঙ্গারা আর দুইটা সমুচা একটু তাড়া...  
2    পাগলা হাওয়ার বাদল দিনে পাগল আমার মন জেগে ওঠে প...  
3    যুদ্ধ আনে ধ্বংস সজনী সজনী তোমারে দেখিয়া মাতাল ...  
4                                                  NaN  
..                                                 ...  
251                                                NaN  
252                                                NaN  
253                                                NaN  
254                                                NaN  
255                                                NaN  

[256 rows x 5 columns]

In [ ]:
# Fetch Bengali stopwords from Stopwords-ISO
import requests

url = "https://raw.githubusercontent.com/stopwords-iso/stopwords-bn/master/stopwords-bn.txt"
response = requests.get(url)
bengali_stopwords = response.text.splitlines()

print("Total Bengali Stopwords:", len(bengali_stopwords))

Total Bengali Stopwords: 398


In [ ]:
banglish_stopwords = [
    "ami", "tumi", "she", "amra", "tomra", "tara", "kono", "onek", "kichu",
    "kintu", "shudhu", "jeta", "ki", "keno", "kothay", "jokhon", "tokhon",
    "abar", "ekhane", "othoba", "ba", "keu", "jodi", "chilo", "achhe", "korchi",
    "korbo", "bolchi", "dite", "niye", "jeta", "hoye", "jay", "ache", "korar",
    "bhalo", "kharap", "ar", "shesh", "jabo", "ashbo", "bolbe", "korle", "ja",
    "na", "ei", "eta", "shei", "nah"
]

In [ ]:
# Combine Bengali stopwords with Banglish stopwords
combined_stopwords = set(bengali_stopwords + banglish_stopwords)

print("Total Combined Stopwords:", len(combined_stopwords))

Total Combined Stopwords: 446


In [ ]:
def clean_text(text):
    text = re.sub(r'[^a-zA-Z\u0980-\u09FF ]', '', text)  # Keep Bengali characters

    # Tokenize the text
    words = word_tokenize(text)

    # Remove stopwords (English and Bengali)
    stop_words = set(stopwords.words('english'))
    bengali_stopwords = combined_stopwords
    stop_words.update(bengali_stopwords)
    words = [word for word in words if word.lower() not in stop_words and len(word) > 1]

    return words

In [ ]:
df['cleaned_text'] = df['Visual texts'].apply(clean_text)
df

reel_id  isSafe UnsafeType  \
0    www.facebook.com/reel/1000188341415358       1       Safe   
1    www.facebook.com/reel/1006146964533997       1       Safe   
2    www.facebook.com/reel/1007123741459823       0      Adult   
3    www.facebook.com/reel/1007420607202244       1       Safe   
4    www.facebook.com/reel/1008519870870927       1       Safe   
..                                      ...     ...        ...   
251   www.facebook.com/reel/997262608752854       0      Adult   
252   www.facebook.com/reel/997300345735398       0    Harmful   
253   www.facebook.com/reel/998187401354206       1       Safe   
254   www.facebook.com/reel/999558344609179       1       Safe   
255   www.facebook.com/reel/999669865038215       1       Safe   

                                          Visual texts  \
0       Me on my way to watch Oppenheimer After Berbie   
1                               কোন টেক্সট পাওয়া যায়নি   
2         বান্ধবী আমার লাগানির পিনিকে আছে Love in love   
3         প্রত্যেকটা অফিসে এমন একজন কলিগ থাকবেই Laptop   
4            হ্যালো শার্ক ট্যাঙ্ক বাংলাদেশ আই এম কামিং   
..                                                 ...   
251                             কোন টেক্সট পাওয়া যায়নি   
252                             কোন টেক্সট পাওয়া যায়নি   
253  খবরঃ কয়লা নিয়ে মোংলা বন্দরে এলো চীনের জাহাজ দে...   
254          সাকিব আল হাসান to বাংলাদেশী ক্রিকেট ফ্যান   
255                             কোন টেক্সট পাওয়া যায়নি   

                                           Audio texts  \
0                                                  NaN   
1    এ মামা দুইটা সিঙ্গারা আর দুইটা সমুচা একটু তাড়া...   
2    পাগলা হাওয়ার বাদল দিনে পাগল আমার মন জেগে ওঠে প...   
3    যুদ্ধ আনে ধ্বংস সজনী সজনী তোমারে দেখিয়া মাতাল ...   
4                                                  NaN   
..                                                 ...   
251                                                NaN   
252                                                NaN   
253                                                NaN   
254                                                NaN   
255                                                NaN   

                                          cleaned_text  
0                    [way, watch, Oppenheimer, Berbie]  
1                               [টেক্সট, পাওয়া, যায়নি]  
2               [বান্ধবী, লাগানির, পিনিকে, Love, love]  
3      [প্রত্যেকটা, অফিসে, একজন, কলিগ, থাকবেই, Laptop]  
4        [হ্যালো, শার্ক, ট্যাঙ্ক, বাংলাদেশ, এম, কামিং]  
..                                                 ...  
251                             [টেক্সট, পাওয়া, যায়নি]  
252                             [টেক্সট, পাওয়া, যায়নি]  
253  [খবরঃ, কয়লা, মোংলা, বন্দরে, এলো, চীনের, জাহাজ,...  
254      [সাকিব, আল, হাসান, বাংলাদেশী, ক্রিকেট, ফ্যান]  
255                             [টেক্সট, পাওয়া, যায়নি]  

[256 rows x 6 columns]

In [ ]:
word_frequencies = {}

# Iterate through the cleaned text and update frequencies
for index, row in df.iterrows():
    for word in row['cleaned_text']:
      word = word.lower()
      if word in word_frequencies:
          word_frequencies[word] += 1
      else:
          word_frequencies[word] = 1

In [ ]:
sorted_frequencies = dict(sorted(word_frequencies.items(), key=lambda item: item[1], reverse=True))

In [ ]:
for word, frequency in sorted_frequencies.items():
    print(f'{word}: {frequency}')

যায়নি: 98
টেক্সট: 97
পাওয়া: 97
স্যার: 21
একটা: 17
ভাই: 13
kuk: 13
বন্ধু: 12
বউ: 12
বলি: 12
কথা: 11
যায়: 11
মানে: 9
হয়ে: 9
তোর: 9
হলুদ: 9
বড়: 7
বয়স্ক: 7
পিচ্চি: 7
life: 7
গরম: 7
shajalal: 6
kabir: 6
হরতাল: 6
আচ্ছা: 6
akta: 6
talking: 6
bro: 6
তোমাকে: 5
মিস: 5
সাথে: 5
কেমন: 5
ছেলে: 5
বাবা: 5
বলছি: 5
দেবো: 5
amar: 5
islam: 5
স্বামী: 5
দিয়ে: 5
সমস্যা: 5
ফ্রিজ: 5
একদম: 4
রাত: 4
দুলাভাই: 4
মেয়ে: 4
জল: 4
হ্যাঁ: 4
টাওয়ার: 4
কোথায়: 4
মারা: 4
লে: 4
যখনই: 4
জীবন: 4
শালী: 4
afrin: 4
২০২৪: 4
গিন্নী: 4
সকাল: 4
মুখে: 4
রাখতে: 4
মশাই: 4
ড্যান্স: 4
কন: 4
oh: 4
ফাইট্টা: 4
guitar: 4
seconds: 4
love: 3
বাংলাদেশ: 3
দিবো: 3
সাবধান: 3
ভাত: 3
সময়: 3
পরীক্ষা: 3
লাইট: 3
আওয়ামীলীগ: 3
সবাই: 3
nura: 3
টোটো: 3
লাও: 3
কাছেই: 3
বউয়ের: 3
ওটা: 3
তাড়াতাড়ি: 3
নিউমোনিয়া: 3
ছাদ: 3
ঘরটা: 3
টাকা: 3
দেখলে: 3
goal: 3
kotha: 3
munmum: 3
গ্যাস: 3
কয়দিন: 3
দাও: 3
এক: 3
পুলিশ: 3
আসে: 3
ভালোবাসা: 3
বন্ধ: 3
chele: 3
বছর: 3
ক্যামেরা: 3
হয়নি: 3
bangla: 3
desh: 3
সেদিন: 3
বুঝলেন: 3
খাবার: 3
তোরা: 3
কিনেছি: 3
কার: 3
er: 3
antik: 3
ke: 3

## Word2vec

In [ ]:
tokenized_data = df['cleaned_text'].tolist()
tokenized_data

[['way', 'watch', 'Oppenheimer', 'Berbie'],
 ['টেক্সট', 'পাওয়া', 'যায়নি'],
 ['বান্ধবী', 'লাগানির', 'পিনিকে', 'Love', 'love'],
 ['প্রত্যেকটা', 'অফিসে', 'একজন', 'কলিগ', 'থাকবেই', 'Laptop'],
 ['হ্যালো', 'শার্ক', 'ট্যাঙ্ক', 'বাংলাদেশ', 'এম', 'কামিং'],
 ['ইন্ডিয়ান',
  'কাক্কু',
  'আহ',
  'সোনা',
  'গো',
  'একদম',
  'পয়েন্টে',
  'গিয়া',
  'মেইন',
  'জয়েন্টে',
  'লাগছে'],
 ['Jelous', 'Loyalty'],
 ['টেক্সট', 'পাওয়া', 'যায়নি'],
 ['Shajalal',
  'Kabir',
  'বোনঃ',
  'দিদি',
  'রাত',
  '১২টা',
  'বাজে',
  'দুলাভাই',
  'এখনো',
  'বাসায়',
  'আসলো',
  'মেয়ে',
  'ফূর্তি',
  'দিদিঃ',
  'একটা',
  'থাপ্পর',
  'দিবো',
  'সবসময়',
  'নেগেটিভ',
  'চিন্তা',
  'করিস',
  'রাস্তায়',
  'গাড়ির',
  'নিচে',
  'চাপা',
  'যেতেও'],
 ['টেক্সট', 'পাওয়া', 'যায়নি'],
 ['বন্ধু', 'সাবধান', 'সাবধান'],
 ['টেক্সট', 'পাওয়া', 'যায়নি'],
 ['টেক্সট', 'পাওয়া', 'যায়নি'],
 ['টেক্সট', 'পাওয়া', 'যায়নি'],
 ['আহারে', 'ভাত', 'খেয়ে', 'আছি', 'চোখে', 'জল', 'আসলো'],
 ['টেক্সট', 'পাওয়া', 'যায়নি'],
 ['টেক্সট', 'পাওয়া', 'যায়নি'],
 ['টেক্সট', 'পাওয়া

In [ ]:
import gensim
from gensim.models import Word2Vec

In [ ]:
word2vec_model = Word2Vec(
    sentences=tokenized_data,
    vector_size=100,  # Embedding dimension
    window=7,         # Window size
    sg=1,             # Use skip-gram (1 for skip-gram, 0 for CBOW)
    min_count=1,      # Minimum word frequency
    workers=4         # Number of worker threads
)

In [ ]:
word2vec_model.save("word2vec_model.model")

In [ ]:
word2vec_model.wv['বয়স্ক']

array([-0.00069453,  0.0134047 ,  0.00410861, -0.00295028,  0.01014801,
       -0.01680136,  0.01076722,  0.0129148 , -0.00778613, -0.00589263,
       -0.00713523, -0.01470695,  0.00750425, -0.00218558,  0.00766395,
       -0.01762038,  0.00115749, -0.00822753,  0.01089997, -0.01551907,
        0.01243925,  0.00143106, -0.00661726, -0.00498537, -0.00916565,
       -0.00352319, -0.01100145, -0.01480282,  0.00215888,  0.00092279,
        0.00412994,  0.00146106, -0.00981293, -0.00295077,  0.00799659,
        0.01721746, -0.01367074, -0.00019413, -0.00245323, -0.01371306,
        0.00801606, -0.01304703,  0.00922308,  0.00995607,  0.00319638,
       -0.01113181, -0.00759384, -0.00738113,  0.00404919,  0.00527915,
        0.00820769,  0.0082622 ,  0.00484618, -0.00262288,  0.00521623,
        0.00271226,  0.00969152,  0.00593093, -0.00340906,  0.00360584,
       -0.00273542, -0.00319876, -0.00896749,  0.00024759, -0.00177381,
       -0.00118359,  0.00069408,  0.00403483,  0.00483081, -0.00

In [ ]:
word2vec_model.wv['GOAL']

array([ 6.68998691e-04,  6.53891172e-03, -1.93139224e-03,  1.49941465e-04,
        9.09017399e-03,  3.13863321e-03, -9.40521993e-03, -3.41349072e-03,
       -6.79454906e-03, -6.07006950e-04,  9.19017568e-03,  6.03484362e-03,
        7.80452415e-03, -5.72877005e-03,  1.07624358e-03, -2.05068104e-03,
       -8.72773398e-03,  3.73446522e-03, -7.80828670e-03, -1.30145982e-05,
        2.12349719e-03, -5.40423440e-03,  9.39636584e-03,  3.12487036e-03,
        2.86503136e-03,  4.13964596e-03, -6.84729312e-03, -2.34192167e-03,
       -3.60686681e-04,  5.43741370e-03, -6.21825736e-03,  7.00698560e-03,
       -7.02873943e-03,  7.72593310e-04, -2.39129877e-03, -3.46982153e-03,
       -8.96446127e-03,  8.40197550e-04, -9.11477953e-03, -2.89680017e-03,
        2.21945625e-03, -1.54347718e-03, -1.71218126e-03,  6.52780663e-03,
       -4.92253341e-03,  1.60076714e-04, -6.45373994e-03, -4.44085663e-03,
       -9.99897951e-04, -9.00207832e-03,  1.01282485e-02,  8.73955246e-03,
       -3.88555671e-03, -

In [ ]:
len(word2vec_model.wv.index_to_key)

1401

In [ ]:
def get_sentence_embedding(sentence, model):
    tokens = [token for token in tokenized_data]
    embeddings = [model.wv[token] for token in tokens if token in model.wv]
    if embeddings:
        return sum(embeddings) / len(embeddings)  # Average embedding for the sentence
    else:
        return None

In [ ]:
for tokens in tokenized_data:
  for token in tokens:
    print(token)
    print(word2vec_model.wv[token])
  print()

Streaming output truncated to the last 5000 lines.
  2.2020223e-04 -4.6260250e-03  2.3616271e-03  5.4584248e-03
 -7.1943486e-03 -4.8563154e-03 -2.9207178e-04  4.0966435e-03
  8.8301757e-03  4.5789103e-03 -6.5483288e-03 -1.9057343e-03
 -5.1780865e-03  9.9594975e-03 -7.8353668e-03  5.4361629e-03
  9.1792848e-03 -6.6246591e-03  6.3313390e-03 -9.5950980e-03
  9.6855564e-03  9.6302042e-03  7.6784990e-03  7.7441079e-03
  1.6503376e-05  8.8817172e-04 -5.8388310e-03 -7.3718373e-03
  1.6895646e-03  7.5327340e-03 -1.3148462e-03  4.9087014e-03
 -7.0387400e-03  3.9943513e-03 -4.2688339e-03  1.3345330e-04
 -9.6124345e-03 -6.8874666e-03 -8.2592536e-03 -4.7157919e-03
  3.6606817e-03  1.0220614e-02  1.1236644e-03  6.8214810e-03
 -7.3654754e-03 -5.4003494e-03  6.0901842e-03  6.3276105e-04
  6.2837796e-03 -9.0335170e-03  1.4678618e-03  8.7831067e-03
 -1.7244895e-03 -5.7717809e-03  2.3215814e-03  6.7061847e-03
 -4.0774513e-03 -2.6503187e-03  2.6989756e-03 -5.1862006e-03
 -8.3035082e-03  9.5760468e-03 -5.

# FastText

In [ ]:
from gensim.models import FastText

In [ ]:
fasttext_model = FastText(
    sentences=tokenized_data,
    vector_size=100,  # Embedding dimension
    window=5,         # Window size
    sg=1,             # Use skip-gram (1 for skip-gram, 0 for CBOW)
    min_count=1,      # Minimum word frequency
    workers=4,        # Number of worker threads
    word_ngrams=1     # Character n-gram size
)

In [ ]:
fasttext_model.save("fasttext_model.model")

In [ ]:
fasttext_model.wv['বয়স্ক']

array([-8.8852842e-04,  1.6328545e-03,  5.7711866e-04,  9.7112771e-04,
        4.6862732e-03, -1.0361290e-02, -4.5491024e-03, -7.6576759e-04,
       -1.3100810e-03, -3.9641140e-03, -2.4287731e-03,  8.2018884e-04,
        3.4903935e-03,  7.6122471e-04,  2.9863261e-03, -4.9666604e-03,
       -1.1203324e-03,  1.2866000e-03,  1.1434611e-03, -5.2243923e-03,
        3.6832190e-03, -2.6107134e-04, -4.3325266e-03,  1.4588316e-03,
       -1.1316580e-03,  1.6005938e-03,  8.8816957e-04,  2.7593030e-04,
       -1.5874616e-04,  8.1514218e-04,  1.0964724e-03, -1.3090291e-03,
        3.9971573e-03, -1.0654203e-03, -1.8103408e-04,  1.0746481e-03,
        2.8425001e-03,  1.2118986e-03, -2.2582978e-03, -1.5278737e-03,
        3.3495703e-03, -9.3430578e-04,  2.6076415e-03, -6.4123424e-06,
        2.9888586e-03,  3.9634695e-03, -7.3452429e-03,  2.3879111e-04,
       -1.8527419e-03, -2.3123026e-03,  4.2165099e-03,  9.0343202e-04,
        1.6173943e-03,  3.6626325e-03,  1.8293160e-03, -1.6402458e-03,
      

In [ ]:
fasttext_model.wv['song']

array([-2.4735506e-03, -4.0615248e-03,  7.4784370e-04,  3.8836137e-04,
        1.3874661e-03, -2.7512826e-03, -4.9125711e-03, -2.1075455e-03,
       -1.2376420e-03, -7.5956504e-04, -3.4366127e-03,  2.5773951e-04,
       -2.3540804e-04,  1.2533885e-03,  4.3517718e-04,  1.5271016e-04,
       -2.4166991e-04, -1.7533963e-05,  5.4422207e-03, -2.7243776e-04,
        2.8303799e-03,  2.2813636e-03, -4.5719798e-04, -1.6917735e-04,
       -1.3976203e-03, -5.5284554e-04, -1.7564005e-03,  2.4675229e-03,
        1.4305742e-03,  2.6789290e-04,  3.6042191e-03, -4.0275953e-03,
        4.1023223e-03,  2.0778470e-03,  2.9009799e-03,  6.4135951e-05,
        5.3084071e-04,  6.7070860e-04, -1.9686497e-03, -2.4401662e-03,
        1.7912167e-03, -2.4458119e-03, -1.0058521e-03, -8.9725497e-04,
        1.7688926e-03,  2.8490624e-03, -1.9644352e-03, -6.0402055e-04,
        1.5861805e-03, -3.9167567e-03,  4.6764286e-03, -5.4449858e-03,
       -1.3174260e-03,  5.3292145e-03,  3.7064846e-03,  6.0666737e-04,
      

In [ ]:
fasttext_model.wv['bipod']

array([ 7.3523587e-04, -2.3961323e-03, -1.0297131e-03, -2.5288586e-03,
       -3.4779869e-03,  1.4400863e-03, -1.5711406e-03, -1.5115967e-03,
       -2.4441448e-03,  1.2281673e-03,  8.0558391e-05, -8.7540262e-05,
       -1.6086174e-03,  2.1784275e-03, -6.5570930e-04, -1.5488351e-03,
       -1.6258667e-03,  1.6206696e-04,  1.5509472e-03,  3.9883903e-03,
        1.6220777e-03,  1.2895784e-03,  6.8066554e-04, -2.0124717e-04,
        2.4005692e-03, -1.7175388e-03,  3.5628016e-04,  1.5932812e-03,
       -7.6889590e-04,  2.0826722e-03,  1.3655791e-03,  1.7224426e-03,
        1.7527072e-04,  1.0909606e-04, -7.0250675e-04, -1.3137460e-03,
        7.8743289e-04,  1.8111912e-03,  3.7589748e-04,  7.7393866e-04,
       -1.0246385e-03, -5.4180936e-04,  1.9279783e-05, -1.3695352e-03,
        3.6243456e-03,  2.0979960e-03, -4.5530917e-04,  2.1636362e-04,
       -9.5645647e-04,  8.6807268e-04,  7.0257951e-04, -2.2176839e-03,
       -4.1742227e-03, -1.9861127e-03, -2.1120766e-04,  2.0391815e-03,
      

In [ ]:
df.to_csv("preprocessed_text.csv", index=False)